name: MouBieAPI

version: '${project.version}'
api-version: ${plugin.api.version}

authors: [ MouBieCat ]
description: '${project.description}'

main: com.moubieapi.MouBieCat

commands:
  MouBieAPI:
    description: "該插件的主要命令。"
    permission: "MouBieAPI.admin"
    aliases: [ mbi ]

permissions:
  MouBieAPI.admin:
    description: "查看有關 MouBieAPI 依賴庫相關的說明。。"
