name: MouBieAPI

version: '${project.version}'
api-version: ${plugin.api.version}

authors: [ MouBieCat ]
description: '${project.description}'

main: com.moubieapi.MouBieCat

commands:
  MouBieAPI:
    description: "該插件的主要命令。"
    aliases: [ mbi ]

permissions:
  MouBieAPI.view:
    description: "查看當前由 MouBieCat 旗下所開發所有插件介面。"
